procedure fpunch();

begin

ClrScr;
    writeln('================================================');
    writeln('|      o                             <         |');
    writeln('|     \|_                           \|/        |');
    writeln('|      /                             |         |');
    writeln('|     / \                           / \        |');
    writeln('================================================');
    delay(800);
    ClrScr;
    writeln('================================================');
    writeln('|      o                             <         |');
    writeln('|     \|====                        \|/        |');
    writeln('|      \                             !         |');
    writeln('|     / \                           / \        |');
    writeln('================================================');      
    sndPlaySound('.\sounds\characterHitHeavy.wav', snd_Async or snd_NoDefault); 
    delay(500);
    sndPlaySound('.\sounds\genericEnemyHurt.wav', snd_Async or snd_NoDefault); 
    delay(800);
    ClrScr;
    writeln('================================================');
    writeln('|      o                             <         |');
    writeln('|     \|-                           \|/        |');
    writeln('|      |                             |         |');
    writeln('|     / \                           / \        |');
    writeln('================================================');
    delay(800);
    ClrScr;
    writeln('================================================');
    writeln('|      o                             <         |');
    writeln('|     \|/                           \|/        |');
    writeln('|      |                             |         |');
    writeln('|     / \                           / \        |');
    writeln('================================================');
    delay(800);
end;